### ISSUE TITLE
Add program filters

### ISSUE THREAD

**Issue by evenh** [javaBin/javazone.no#69]
An improvement to the program pages would be to add some sort of filtering mechanism in order to just view lightning talks, workshops etc.

Also, a possibility to filter by by spoken language would be beneficial to the international audience I would guess.

**Comment by Espenhh** [comment]
Filters similar to last year (https://2016.javazone.no/program) will be added before the conference, we just need to get the timestamps deployed first :)

**Comment by bendiksolheim** [comment]
Aaaaaan they are live :) https://2017.javazone.no/program

**Comment by evenh** [comment]
Awesome, thanks!
